### PR TITLE
update demo.launch for using actual robot

### PR DESCRIPTION
**Pull request by YoheiKakiuchi**
I added the same arguments in demo.launch in hydro-devel and added use_actual_robot for using actual robot(PR2) with demo.launch .

### CODE REVIEW

**Comment by sachinchitta** [comment]
+1

I like these changes a lot - might be worthwhile propagating them upwards to the setup assistant so this is generated for all robots.

**Comment by sachinchitta** [comment]
Could you do a pull request against groovy-devel instead of hydro-devel?

**Comment by YoheiKakiuchi** [comment]
I created new pull request against groovy-devel
https://github.com/ros-planning/moveit_pr2/pull/48

**Comment by isucan** [comment]
I am not too happy about these changes. These launch files should be close to what is generated by the moveit_setup_assistant.

**Pull request closed without merging**
