### PR TITLE
add tutorial for apply_planning_scene service

### PR DESCRIPTION
**Pull request by v4hn**
This documents the API proposed in https://github.com/ros-planning/moveit_ros/pull/686 .
@davetcoleman: Here you go.

Now time to go to bed over here. :-)

### CODE REVIEW

**Comment by davetcoleman** [comment]
:open_mouth: OMG amazing - someone added to a tutorial! :sparkles:

waiting for moveit_ros PR to be merged

**Comment by davetcoleman** [comment]
ros-planning/moveit_ros#686 passed, merging

perhaps announce on moveit-users?

**Comment by v4hn** [comment]
On Wed, Jun 15, 2016 at 11:31:50PM -0700, Dave Coleman wrote:

> ros-planning/moveit_ros#686 passed, merging
> 
> perhaps announce on moveit-users?

How about doing this once moveit_ros/indigo-devel is actually
released to make the feature publicly available?

@130s: how about releasing moveit_ros? Should we include
some other pull-requests there before that?

**Comment by 130s** [comment]
When the consensus is made give a "go" then I'll be gone :)

**Pull request merged**
