### PR TITLE
migrate moveit_full_pr2 from ros-planning/moveit

### PR DESCRIPTION
**Pull request by rhaschke**
Migrate moveit_full_pr2 from https://github.com/ros-planning/moveit/pull/1111 to resolve a circular package dependency.
`moveit_full_pr2` depends on:
`moveit_pr2` -> `pr2_moveit_plugins` -> `moveit_*`
Thus, this meta-package belongs here and not into the moveit repo.

Also cherry-pick this to kinetic-devel, replacing dependency to `moveit_full` in package.xml with actual packages?

### CODE REVIEW

**Review by 130s — APPROVED** [review]
But CI is failing for some reason. I can take a brief look.

**Comment by rhaschke** [comment]
> But CI is failing for some reason. I can take a brief look.

Looks like the indigo-devel branch of this repo is failing for ages on Travis: https://travis-ci.org/ros-planning/moveit_pr2/branches. Does anybody actively maintain this branch?
Besides `kdl`, which was probably renamed `orocos_kdl`, there are some other strange package names, I never heard about before, like `planning_models`...

**Comment by 130s** [comment]
> Looks like the indigo-devel branch of this repo is failing for ages on Travis: https://travis-ci.org/ros-planning/moveit_pr2/branches.

That could mean the failing CI *may* not matter much, at least in the ROS distro release infrastructure.

Since this PR is a blocker for https://github.com/ros-planning/moveit/pull/1111 and ultimately https://github.com/ros-planning/moveit/issues/1000, I'm merging this PR (then fix the failing CI separately).

**Comment by 130s** [comment]
(Btw @rhaschke, you shouldn't have committed directly such as https://github.com/ros-planning/moveit_pr2/commit/dbecd98f5711e3630f2ecd44464e2c46ad392111. You could have added those hotfix attempts to this PR IMO ;).

**Pull request merged**
