### PR TITLE
Fix Travis issues

### PR DESCRIPTION
**Pull request by rhaschke**
Base Travis build on MoveIt's source containers.
Also, enable `catkin_lint` + `clang-format`.

### CODE REVIEW

**Comment by v4hn** [comment]
Oh, I guess you get travis mails for this package? :smile: 
Sorry for the inconvenience and thanks for the effort already!

**Comment by v4hn** [comment]
Oh, you directly pushed this to upstream? :confused: 
Now `kinetic-devel` fails with
```
$ .moveit_ci/travis.sh
Unsupported ROS_REPO=. Use 'ros' or 'ros-shadow-fixed'
```
though.

**Comment by rhaschke** [comment]
> Oh, you directly pushed this to upstream?

Oops. This was not intended! I'm already working on a fix.

**Comment by rhaschke** [comment]
I resetted kinetic-devel and filed a new PR for this: #103.

**Pull request closed without merging**
