### PR TITLE
Remove pr2_moveit_tutorials

### PR DESCRIPTION
**Pull request by davetcoleman**
This repo has now been moved to https://github.com/ros-planning/moveit_tutorials

I don't think this should be merged until the dust of the move settles and more discussion has happened, but I wanted to create this now for future reference

See https://github.com/ros-planning/moveit/issues/36#issuecomment-241596120 for more discussion

### CODE REVIEW

**Comment by v4hn** [comment]
Do we really want to remove this package, that has been released in indigo(!) from our indigo-branch?
@130s is it possible to remove the `pr2_moveit_tutorials` package from the ROS indigo distribution?
If that's no problem, I'm fine with it.

Alternatively  we could add some note to the package in indigo that says that it has been moved and instead remove it in a new `jade-devel` branch.

@dornhege what do you think?

**Comment by davetcoleman** [comment]
Ah good point - I think moveit_pr2 should branch for jade and we remove it there. While we branch for Jade we should get all our tutorials working in Jade - I don't think they all do yet

**Comment by 130s** [comment]
Removing a package from the list of the released packages is possible (just remove an entry for the package from rosdistro).

**Comment by davetcoleman** [comment]
Yes but I'm pretty sure that is frowned upon in an LTS

**Comment by v4hn** [comment]
I just created a `jade-devel` branch in this repo.
Could you retarget this request to this branch?

**Comment by v4hn** [comment]
I just noticed that now we can't build both `moveit_tutorials` and `moveit_pr2` in the same workspace as both create the same binaries:

>   add_executable cannot create target "kinematic_model_tutorial" because
>   another target with the same name already exists.

In my opinion this justifies to remove `pr2_moveit_tutorials` in indigo too.

**Comment by davetcoleman** [comment]
> In my opinion this justifies to remove pr2_moveit_tutorials in indigo too.

I kind of agree. I could also just rename the executable in moveit_tutorials. I don't care either way.

**Comment by v4hn** [comment]
merged. I believe it is more important to have `moveit_pr2` and `moveit_tutorials` built in the same workspace than keeping the package in indigo.

**Comment by davetcoleman** [comment]
great. perhaps we should just remove the jade-devel branch you created, then

**Comment by v4hn** [comment]
On Fri, Aug 26, 2016 at 01:02:13PM -0700, Dave Coleman wrote:

> great. perhaps we should just remove the jade-devel branch you created, then

I already did that. :)

**Pull request merged**
