### PR TITLE
use urdf typedefs to stay compatible with boost vs std ptrs

### PR DESCRIPTION
**Pull request by v4hn**
allow to compile the package with a current version of urdf

### CODE REVIEW

**Comment by bmagyar** [comment]
Could/should the same be applied to `pr2_moveit_tests`, [here](https://github.com/ros-planning/moveit_pr2/blob/kinetic-devel/pr2_moveit_tests/kinematics/src/test_kinematics_as_plugin.cpp#L167) for instance?

**Comment by v4hn** [comment]
That's true, I don't build the tests here, so I didn't notice.

**Comment by v4hn** [comment]
I pushed a follow-up that adjusts the tests.
I didn't build them, but CI will check.

**Review by bmagyar — APPROVED** [review]

**Comment by bmagyar** [comment]
Thanks!!

**Pull request merged**
